# use '!!str' to force numbers to be read as strings if they are being read as times

---


newSiteConfigsVersion: 
oldVersion: !!str 
components:
    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        server:
          type: service
          vm: <vm_to_download_to>
          service_name: <templated_service_name>
        # configs for client app
        client:
          type: app
          vm: <vm_to_download_to>
          appDestination: /path/to/destination
          path: <templated_path_to_download_location>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        appDestination: /path/to/destination
        path: <templated_path_to_download_location>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        path: <templated_path_to_download_location>
        options: -disableOnly

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed:
      version:
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed: 
      version: 
      Agent:
        changed: 
        version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed: 
      version: 
      Agent:
        changed: 
        version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # component name
    - name: <component_name>
      changed:
      version:
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>

    # ------------------- Non-Startup Tool Components -------------------
    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        appDestination: /path/to/destination
        path: <templated_path_to_download_location>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        service_name: <templated_service_name>(Instance 1)

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        path: <templated_path_to_download_location>
        shortcut_name: <templated_service_name>
        first_app:
          name: <component_name>
          appDestination: /path/to/destination
        second_app:
          name: <component_name>
          appDestination: /path/to/destination

    # component name
    - name: <component_name>
      changed: 
      version: !!str
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: service
        vm: <vm_to_download_to>
        service_name: <templated_service_name>
      symlink:
        location: E:\Program Files\Symbotic\Integration Manager {0}
        symlink_name: <templated_service_name>
        target: E:\SiteConfigs {0}

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        appDestination: /path/to/destination
        path: <templated_path_to_download_location>

    # component name
    - name: <component_name>
      changed: 
      version: 
      # DO NOT CHANGE ANYTHING UNDER THIS COMMENT
      configs:
        type: app
        vm: <vm_to_download_to>
        appDestination: /path/to/destination
        path: <templated_path_to_download_location>
